// <auto-generated />
namespace Test3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddStringLengthInPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStringLengthInPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201912092043194_AddStringLengthInPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
